# Font settings
font_family             FiraCode Nerd Font
bold_font               auto
italic_font             auto
bold_italic_font        auto
font_size               11.0

# Features
font_features FiraCode-Regular +cv02 +ss08 +ss02 +ss03 +ss04 +ss05
font_features FiraCode-Bold    +cv02 +ss08 +ss02 +ss03 +ss04 +ss05
font_features FiraCode-Retina  +cv02 +ss08 +ss02 +ss03 +ss04 +ss05

# Window settings
background_opacity      0.8
window_padding_width    10
hide_window_decorations yes
confirm_os_window_close 0

# Colors
foreground              #f2f2f2
background              #131313
selection_foreground    #131313
selection_background    #F4DBD6

cursor                  #F4DBD6
cursor_text_color       #131313
url_color               #F0C6C6

# Black
color0 #494D64
color8 #5B6078

# Red
color1 #ED8796
color9 #ED8796

# Green
color2  #A6DA95
color10 #A6DA95

# Yellow
color3  #EED49F
color11 #EED49F

# Blue
color4  #8AADF4
color12 #8AADF4

# Magenta
color5  #F5BDE6
color13 #F5BDE6

# Cyan
color6  #8BD5CA
color14 #8BD5CA

# White
color7  #B8C0E0
color15 #A5ADCB
