# Font settings
font_family             FiraCode Nerd Font
bold_font               auto
italic_font             auto
bold_italic_font        auto
font_size               10.0

# Features
font_features FiraCode-Regular +cv02 +ss08 +ss02 +ss03 +ss04 +ss05
font_features FiraCode-Bold    +cv02 +ss08 +ss02 +ss03 +ss04 +ss05
font_features FiraCode-Retina  +cv02 +ss08 +ss02 +ss03 +ss04 +ss05

# Window settings
background_opacity      0.8
window_padding_width    6 14
hide_window_decorations yes
confirm_os_window_close 0

# Key mapping
map ctrl+backspace   send_text all \x17
map ctrl+delete      send_text all \x1bd

# Colors
foreground              #e2e2e2
background              #101010
selection_foreground    #101010
selection_background    #e2e2e2

cursor                  #e2e2e2
cursor_text_color       #101010
url_color               #6b9ed8

# Black
color0  #1c1c1e
color8  #3a3a3c

# Red
color1  #e78284
color9  #e78284

# Green
color2  #7dc48a
color10 #8dd49a

# Yellow
color3  #d4a57c
color11 #e8b98c

# Blue
color4  #6b9ed8
color12 #7aacdb

# Magenta
color5  #b47db0
color13 #c48fc0

# Cyan
color6  #5ab4c8
color14 #6bbcce

# White
color7  #c8c8cc
color15 #e2e2e2
