wallpaper {
    monitor = DP-1
    path = /home/mieszko/.config/hypr/wallpaper_main.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/mieszko/.config/hypr/wallpaper_left.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = /home/mieszko/.config/hypr/wallpaper_laptop.png
    fit_mode = cover
}

splash = false
