background {
    monitor =
    path = /home/mieszko/.config/hypr/wallpaper.png
    color = rgba(16, 16, 16, 1.0)
    blur_passes = 2
    blur_size = 4
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

label {
    monitor =
    text = $TIME
    color = rgba(226, 226, 226, 0.9)
    font_size = 80
    font_family = Inter Bold
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 240, 40
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.08)
    inner_color = rgba(28, 28, 30, 0.95)
    font_color = rgba(226, 226, 226, 1.0)
    fade_on_empty = true
    placeholder_text =
    hide_input = false
    rounding = 20
    check_color = rgba(107, 158, 216, 0.9)
    fail_color = rgba(231, 130, 132, 0.9)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgba(212, 165, 124, 0.9)
    position = 0, -60
    halign = center
    valign = center
}
