background {
    monitor =
    path = /home/mieszko/.config/hypr/wallpaper.png
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2
    reload_time = 0
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

label {
    monitor =
    text = $TIME
    color = rgba(216, 222, 233, 0.80)
    font_size = 80
    font_family = FiraCode Nerd Font Bold
    position = 0, 20
    halign = center
    valign = center
}
